In [2]:
#the usuals
import pandas as pd
import numpy as np
%load_ext autoreload
%autoreload 2

In [3]:
#bringing in the helper functions
from helper import *

In [4]:
path='/home/rachel/Galvanize/capston1/data/'

In [5]:
df = pd.read_json(path+'COAL.json', orient = 'index')#.iloc[:1000,:]

In [6]:
df.head()

,name,units,f,description,copyright,source,iso3166,geography,start,end,last_updated,geoset_id,data,lat,lon,geography2,latlon,lat2,lon2,latlon2
COAL.ASH_CONTENT.OH-3.A,Ash content : Ohio : electric utility cogen : ...,percent,A,Power plants owned by regualted electric utili...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2009,2016,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.3.A,"{'2016': 0, '2015': 0, '2014': 0, '2013': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MS-2.Q,Ash content : Mississippi : electric utility n...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.2.Q,"{'2017Q1': 12.837797064489, '2016Q4': 14.03824...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MO-98.Q,Ash content : Missouri : electric power (total...,percent,Q,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",USA-MO,USA-MO,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.98.Q,"{'2017Q1': 4.7233649747318, '2016Q4': 4.716206...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MS-10.Q,Ash content : Mississippi : other industrial :...,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2000Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.10.Q,"{'2017Q1': 0, '2016Q4': 0, '2016Q3': 0, '2016Q...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NEW-1.Q,Ash content : New England (total) : electric u...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.1.Q,"{'2017Q1': 8.4, '2016Q4': 7.68, '2016Q3': 7.87...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(169316, 20)

The coal json file , when put into a data frame has 169316 rows

useful data is nested in a dictionary inside the data column of each row.

The functions from the helper.py, used below, expands the the df to include columns of all the possible keys in the data dictionaries , and fills rows with the corresponding values from the dictionary.

Trying this pipeline with the full coal df seemed to never want to complete and made my computer sound like it was going lift off my desk. so i decided to limit the rows by parsing the name column for anything to do with coal ash

In [7]:
coal_ash_df = df[df['name'].str.match('Ash content')]

In [8]:
coal_ash_df.shape
#only 651 rows. much better

(651, 20)

In [19]:
coal_ash_df

,name,units,f,description,copyright,source,iso3166,geography,start,end,last_updated,geoset_id,data,lat,lon,geography2,latlon,lat2,lon2,latlon2
COAL.ASH_CONTENT.OH-3.A,Ash content : Ohio : electric utility cogen : ...,percent,A,Power plants owned by regualted electric utili...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2009,2016,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.3.A,"{'2016': 0, '2015': 0, '2014': 0, '2013': 0, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MS-2.Q,Ash content : Mississippi : electric utility n...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.2.Q,"{'2017Q1': 12.837797064489, '2016Q4': 14.03824...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MO-98.Q,Ash content : Missouri : electric power (total...,percent,Q,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",USA-MO,USA-MO,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.98.Q,"{'2017Q1': 4.7233649747318, '2016Q4': 4.716206...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MS-10.Q,Ash content : Mississippi : other industrial :...,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2000Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.10.Q,"{'2017Q1': 0, '2016Q4': 0, '2016Q3': 0, '2016Q...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NEW-1.Q,Ash content : New England (total) : electric u...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.1.Q,"{'2017Q1': 8.4, '2016Q4': 7.68, '2016Q3': 7.87...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
COAL.ASH_CONTENT.ID-8.A,Ash content : Idaho : commercial and instituti...,percent,A,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-ID,USA-ID,2000,2014,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.8.A,"{'2014': 10.12, '2013': 10.22, '2012': None, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.MT-10.A,Ash content : Montana : other industrial : annual,percent,A,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2000,2016,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.10.A,"{'2016': 5.15, '2015': 5.15, '2014': 6.16, '20...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.PCC-1.Q,Ash content : Pacific Contiguous (total) : ele...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CA+USA-OR+USA-WA,2008Q1,2017Q1,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.1.Q,"{'2017Q1': 4.5597236556137, '2016Q4': 4.351898...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.PCN-10.A,Ash content : Pacific Noncontiguous (total) : ...,percent,A,Summation of the states in the Pacific Noncont...,None,"EIA, U.S. Energy Information Administration",NaN,USA-AK+USA-HI,2000,2016,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.10.A,"{'2016': 0, '2015': 9.81, '2014': 9.56, '2013'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.OK-94.A,Ash content : Oklahoma : independent power pro...,percent,A,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-OK,USA-OK,2008,2016,2017-07-05T12:04:11-04:00,COAL.ASH_CONTENT.94.A,"{'2016': 16.27, '2015': 15.17, '2014': 14.11, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# pipline in helper.py
#fill_data_vals(coal_ash_df
k = all_keys(coal_ash_df)

In [10]:
new_df = data_to_df(list(k),coal_ash_df)
new_df = concat_to_df(df,new_df)
new_df.head(30)

,name,units,f,description,copyright,source,iso3166,geography,start,end,...,2006Q1,2004Q4,2001Q4,2007Q4,2001,2012Q3,2001Q3,2002Q2,2014Q1,2014Q3
0,Ash content : Ohio : electric utility cogen : ...,percent,A,Power plants owned by regualted electric utili...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2009,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ash content : Mississippi : electric utility n...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Ash content : Missouri : electric power (total...,percent,Q,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",USA-MO,USA-MO,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ash content : Mississippi : other industrial :...,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2000Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Ash content : New England (total) : electric u...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Ash content : New England (total) : other indu...,percent,A,Summation of the states in the census region o...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2000,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Ash content : New England (total) : electric u...,percent,A,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Ash content : Ohio : electric utility : quarterly,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Ash content : Ohio : other industrial : quarterly,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2000Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Ash content : New England (total) : electric p...,percent,A,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Ash content : New England (total) : electric p...,percent,Q,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Ash content : Ohio : independent power produce...,percent,Q,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Ash content : New Hampshire : electric utility...,percent,A,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-NH,USA-NH,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Ash content : New Hampshire : electric utility...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-NH,USA-NH,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Ash content : Ohio : electric power (total) : ...,percent,A,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Ash content : Ohio : electric power (total) : ...,percent,Q,Power plants owned by companies whose primary ...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Ash content : Montana : electric utility non-c...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Ash content : Montana : commercial and institu...,percent,A,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2000,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Ash content : Montana : commercial and institu...,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2000Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,Ash content : Montana : independent power prod...,percent,A,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Ash content : Mississippi : independent power ...,percent,A,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Ash content : Mississippi : independent power ...,percent,Q,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-MS,USA-MS,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Ash content : New England (total) : electric u...,percent,Q,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Ash content : New England (total) : electric u...,percent,Q,Power plants owned by regualted electric utili...,None,"EIA, U.S. Energy Information Administration",NaN,USA-CT+USA-MA+USA-ME+USA-NH+USA-RI+USA-VT,2008Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,Ash content : Ohio : coke plants : annual,percent,A,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2000,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Ash content : Ohio : coke plants : quarterly,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2000Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Ash content : Ohio : independent power produce...,percent,A,Power plants owned by unregulated power compan...,None,"EIA, U.S. Energy Information Administration",USA-OH,USA-OH,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Ash content : Montana : electric utility : annual,percent,A,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Ash content : Montana : other industrial : qua...,percent,Q,The U.S. coal data is collected and prepared f...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2000Q1,2017Q1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Ash content : Montana : electric utility non-c...,percent,A,Power plants owned by regulated electric utilt...,None,"EIA, U.S. Energy Information Administration",USA-MT,USA-MT,2008,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
for i in new_df[:30].iterrows():
    print(i[1])
    print(type(i[1]))

name           Ash content : Ohio : electric utility cogen : ...
units                                                    percent
f                                                              A
description    Power plants owned by regualted electric utili...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 0, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Mississippi : electric utility n...
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 1, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Missouri : electric power (total...
units                                                    percent
f                                                              Q
description    Power plants owned by companies whose primary ...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 2, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Mississippi : other industrial :...
units                                                    percent
f                                                              Q
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 3, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric u...
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 4, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : other indu...
units                                                    percent
f                                                              A
description    Summation of the states in the census region o...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 5, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric u...
units                                                    percent
f                                                              A
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 6, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : electric utility : quarterly
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 7, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : other industrial : quarterly
units                                                    percent
f                                                              Q
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 8, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric p...
units                                                    percent
f                                                              A
description    Power plants owned by companies whose primary ...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 9, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric p...
units                                                    percent
f                                                              Q
description    Power plants owned by companies whose primary ...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 10, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : independent power produce...
units                                                    percent
f                                                              Q
description    Power plants owned by unregulated power compan...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 11, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New Hampshire : electric utility...
units                                                    percent
f                                                              A
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 12, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New Hampshire : electric utility...
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 13, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : electric power (total) : ...
units                                                    percent
f                                                              A
description    Power plants owned by companies whose primary ...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 14, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : electric power (total) : ...
units                                                    percent
f                                                              Q
description    Power plants owned by companies whose primary ...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 15, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Montana : electric utility non-c...
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 16, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Montana : commercial and institu...
units                                                    percent
f                                                              A
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 17, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Montana : commercial and institu...
units                                                    percent
f                                                              Q
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 18, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Montana : independent power prod...
units                                                    percent
f                                                              A
description    Power plants owned by unregulated power compan...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 19, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Mississippi : independent power ...
units                                                    percent
f                                                              A
description    Power plants owned by unregulated power compan...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 20, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Mississippi : independent power ...
units                                                    percent
f                                                              Q
description    Power plants owned by unregulated power compan...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 21, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric u...
units                                                    percent
f                                                              Q
description    Power plants owned by regulated electric utilt...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 22, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : New England (total) : electric u...
units                                                    percent
f                                                              Q
description    Power plants owned by regualted electric utili...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 23, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name                   Ash content : Ohio : coke plants : annual
units                                                    percent
f                                                              A
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 24, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name                Ash content : Ohio : coke plants : quarterly
units                                                    percent
f                                                              Q
description    The U.S. coal data is collected and prepared f...
copyright                                                   None
                                     ...
2012Q3                                                         0
2001Q3                                                         0
2002Q2                                                         0
2014Q1                                                         0
2014Q3                                                         0
Name: 25, Length: 106, dtype: object
<class 'pandas.core.series.Series'>
name           Ash content : Ohio : independent power produce...
units                                                    percent

In [17]:
fill_data_vals(new_df)

NameError: name 'fill_data_vals' is not defined

In [ ]:
coal_ash_df[-86:].head(20)
#tada! a bunch of new columns with yearly measurments inside (al you see is nans in this head statement becasue the data dictionaries are diffent sizes and the columns are all possible keys)

the f column informs you if the row records anually or quarterly

In [34]:
coal_ash_df[-86:]

,name,units,f,description,copyright,source,iso3166,geography,start,end,...,2000Q1,2008,2007,2006,2005,2004,2003,2002,2001,2000
565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.50,10.38,10.66,11.12,9.75,8.97,8.77,0.0,0.0
569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.44,8.60,8.56,8.09,7.61,8.89,10.15,0.0,0.0
648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
coal_ash_df["f"].head()

COAL.ASH_CONTENT.OH-3.A     A
COAL.ASH_CONTENT.MS-2.Q     Q
COAL.ASH_CONTENT.MO-98.Q    Q
COAL.ASH_CONTENT.MS-10.Q    Q
COAL.ASH_CONTENT.NEW-1.Q    Q
Name: f, dtype: object

In [14]:
# i check to see how many rows per state there where
len(coal_ash_df.loc[coal_ash_df['geography']=='USA-AL'])

11

In [15]:
#lets what information they provide for an individual state
coal_ash_df.loc[coal_ash_df['geography']=='USA-AL']['name']

COAL.ASH_CONTENT.AL-1.A     Ash content : Alabama : electric utility : annual
COAL.ASH_CONTENT.AL-9.A          Ash content : Alabama : coke plants : annual
COAL.ASH_CONTENT.AL-94.A    Ash content : Alabama : independent power prod...
COAL.ASH_CONTENT.AL-98.A    Ash content : Alabama : electric power (total)...
COAL.ASH_CONTENT.AL-98.Q    Ash content : Alabama : electric power (total)...
COAL.ASH_CONTENT.AL-3.A     Ash content : Alabama : electric utility cogen...
COAL.ASH_CONTENT.AL-10.Q    Ash content : Alabama : other industrial : qua...
COAL.ASH_CONTENT.AL-9.Q       Ash content : Alabama : coke plants : quarterly
COAL.ASH_CONTENT.AL-1.Q     Ash content : Alabama : electric utility : qua...
COAL.ASH_CONTENT.AL-3.Q     Ash content : Alabama : electric utility cogen...
COAL.ASH_CONTENT.AL-10.A    Ash content : Alabama : other industrial : annual
Name: name, dtype: object

It looks like there is ash content break downs for individual sectors.

I have noticed that some rows are groups of states. Rows that represent individual states have a non null value in  iso3166 colum so below i am makeing a subset df of just coal ash reporting by state with only useful columns [name,f, description, iso3166, and the last 86 columns which are the data]

In [16]:
coal_ash_df.shape

(1302, 106)

In [17]:
# filtering out duplicates by choosing to just look at anual reporting
coal_ash_df = coal_ash_df[coal_ash_df['f']=='A']

In [18]:
coal_ash_df.shape
#this did not filter..... lets keep going and do it in a different way

(327, 106)

In [19]:
# there are 86 columns of years
coal_ash_df.iloc[:,-86:].head()

,2016,2015,2014,2013,2012,2011,2010,2009,2017Q1,2016Q4,...,2000Q1,2008,2007,2006,2005,2004,2003,2002,2001,2000
COAL.ASH_CONTENT.OH-3.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NEW-10.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NEW-2.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NEW-98.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COAL.ASH_CONTENT.NH-1.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# filtering for individual states
coal_ash_df.dropna(subset=['iso3166'],inplace=True)
coal_ash_df.shape

(257, 106)

In order to make a new data fram with just the columns I want, Im going to split and recomdind

In [21]:
# just name and state
coal_ash_df_1= coal_ash_df.filter(items=['name','iso3166'])
coal_ash_df_1.shape

(257, 2)

In [22]:
#just year columns
coal_ash_df_2 = coal_ash_df.iloc[:,-86:]
coal_ash_df_2.shape

(257, 86)

In [23]:
# concatinating the two sets of columns to get only useful info
ash_anual_state_df = coal_ash_df_1.join(coal_ash_df_2)
ash_anual_state_df.shape

(257, 88)

In [24]:
# filtering for just anual data. The new way!
anual_cols = [c for c in ash_anual_state_df.columns if not 'Q' in c]
#lets sort the years while we are at it
ash_anual_state_df = ash_anual_state_df[sorted(anual_cols)]

In [25]:
ash_anual_state_df.shape

(257, 19)

upon inspection it looks like i filtered out some state when i only included rows that did not have nans in the iso6133 column. Lets try this gain and use the geography column that has region and states

In [26]:
coal_ash_df = df[df['name'].str.match('Ash content')]
fill_data_vals( coal_ash_df);

/home/rachel/Galvanize/capston1/energy-statistics/helper.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[i,k] = v

In [27]:
# just name and state
coal_ash_df_1= coal_ash_df.filter(items=['name','geography'])
#just year columns
coal_ash_df_2 = coal_ash_df.iloc[:,-86:]
# concatinating the two sets of columns to get only useful info
ash_anual_state_df = coal_ash_df_1.join(coal_ash_df_2)
# filtering for just anual data. The new way!
anual_cols = [c for c in ash_anual_state_df.columns if not 'Q' in c]
#lets sort the years while we are at it
ash_anual_state_df = ash_anual_state_df[sorted(anual_cols)]
ash_anual_state_df.shape

(1302, 19)

WELL there are alot more rows. lets inspect...

In [32]:
ash_anual_state = ash_anual_state_df['geography'].dropna()

**ash_anual_state_df is a datframe of ash content per state or region per year**

In [ ]:
#ash_anual_state_df.iloc[:,:17]

Lets look at one region and go a little deeper

In [33]:
mountain_ash = ash_anual_state_df[ash_anual_state_df['name'].str.contains('Mountain')]
for i in range(14):
    print(mountain_ash['name'][i])

ValueError: cannot mask with array containing NA / NaN values

In mountain ash data frame there is a row for ash percent per year in each sector

In [ ]:
Lets see which sectors are dirtier

Lets make the sectors into columns and the years into rows for quick sector refernce and change the index to the name column

In [ ]:
mountain_ash = mountain_ash.reset_index().set_index('name')
# and lets drop the "index" column and geography column
mountain_ash.drop(['index',"geography"],axis=1,inplace=True)

In [ ]:
mountain_ash = mountain_ash.T
mountain_ash.head(16)

In [ ]:
# columns to compair for graph (because of all the nans i am going to look at only the last 8 years)
cols = ['Ash content : Mountain (total) : electric utility cogen : annual',
'Ash content : Mountain (total) : electric utility non-cogen : annual', 
'Ash content : Mountain (total) : other industrial : annual',
'Ash content : Mountain (total) : commercial and institutional : annual',
'Ash content : Mountain (total) : independent power producers (total) : annual',
'Ash content : Mountain (total) : electric power (total) : annual']

labels = ['electric utility cogen','electric utility non-cogen','other industrial','commercial and institutional','independent power producers','electric power (total)']

x = [2008,2009,2010,2011,2012,2013,2014,2015,2016]

NOTE: if below cell doesnt work, the above cell that transposes the df was ran to many time. run it again ONCE, then re run below cell

In [ ]:
import matplotlib.pyplot as plt
fig, axs = plt.subplots()
fig.set_size_inches(8,4)

for i, column in enumerate(cols):
    axs.plot(x,mountain_ash[column][-9:],label = labels[i])
    

axs.legend()
axs.set_title('Coal Ash Percent in US Mountain Region')
axs.set_ylabel('Percentage')
axs.set_xlabel('Years')
plt.savefig('images/mountain-ash.png')
;

There are few few things worth noting in this graph. On first inspection "electric utility non-cogen" appears to be missing. Upon further inspection of the data table I saw that non-cogen utility and independent power measurments of ash ar almost exactly the same every year. This make me wonder if almost all independant power producers do not use cogeneration technologies. Also reporting on electric utility plants seems to have stopped in 2012 because all values drop to zero. As a summary I would say that independant power producers, electric utility and other industrial are are not burning coal any cleaner since recording started, but the commercial and industrial is making some changes and I would love to see data in the more recient years. (Remember this is only for the mountain region of the us)

lets take a broader look at each region/states average ash percentage (i would like to sum but the units are percentages)

In [ ]:
ash_anual_groupy = ash_anual_state_df.groupby(['geography']).mean().T
ash_anual_groupy

In [ ]:
ash_anual_groupy.columns

In [ ]:
### lets try and get scatterplot to lay on top of each
x = np.arange(2000,2017)

fig, axs = plt.subplots()
fig.set_size_inches(10,6)
for col in ash_anual_groupy.columns:
    axs.plot(x,ash_anual_groupy[col])
#axs.legend()
axs.set_title('Percent of the total weight of coal burned left over as ash by product')
axs.set_xlabel('Year')
axs.set_ylabel('Ash content (percent)')
#plt.savefig('images/ugly-coal-ash.png');

**WHat happend in 2008??:**
 https://www.eia.gov/coal/review/pdf/feature08.pdf
 - There was a change over in preadents which  may have changed some regulations on the cleanlyness of coal or even how the ash byproduct is reported

lets turn this into a scatter

In [ ]:
### lets try and get scatterplot to lay on top of each
x = np.arange(2000,2017)

fig, axs = plt.subplots()
fig.set_size_inches(10,6)
for col in ash_anual_groupy.columns:
    axs.plot(x,ash_anual_groupy[col],'o')
#axs.legend()
axs.set_title('Percent of the total weight of coal burned left over as ash by product')
axs.set_xlabel('Year')
axs.set_ylabel('Ash content (percent)')
plt.savefig('images/ave-coal-ash.png');

lets make an average average hline. to do so i will ad some colunmns to my data

In [ ]:
ash_anual_groupy['mean'] = ash_anual_groupy.mean(axis=1)
ash_anual_groupy['stdev'] = ash_anual_groupy.std(axis=1)

In [ ]:

x = np.arange(2000,2017)

fig, axs = plt.subplots()
fig.set_size_inches(10,6)
for col in ash_anual_groupy.columns:
    axs.plot(x,ash_anual_groupy[col],'o')
#axs.legend()
axs.set_title('Percent of the total weight of coal burned left over as ash by-product')
axs.set_xlabel('Year')
axs.set_ylabel('Ash content (percent)')

axs.plot(x,ash_anual_groupy['mean'],color='k',label='mean')
axs.plot(x,ash_anual_groupy['mean']+2*ash_anual_groupy['stdev'],'--',color='r',label='2 standard deviations',alpha=.5)
axs.plot(x,ash_anual_groupy['mean']-2*ash_anual_groupy['stdev'],'--',color='r',alpha=.5)
plt.xlim(2001.5,2016.75)
plt.legend()
plt.savefig('images/ave-coal-ash3.png')

**Ash content may not be very revieling . Lets look at CO2 from coal burning over the years**

In [ ]:
#.## reading in TOTAL.json
total_df = json_read(path+'TOTAL.json')
total_df.shape

In [ ]:
total_all_keys = all_keys(total_df)  # all possible yea values (years)
total_data_df = data_to_df(total_all_keys,total_df) # creates a data_df filled with zeros with cols=allkeys.
total_new_df = concat_to_df(total_df,total_data_df)  # concats the data_df to the main df
fill_data_vals(total_new_df)

In [ ]:
#changing the name
totals = total_new_df

In [ ]:
totals.shape

In [ ]:
totals

In [ ]:
# parsing though for the coal rows

coal_totals = totals[totals['name'].str.contains('Coal')]

In [ ]:
coal_totals.iloc[15:,:]

In [ ]:
# lets sub set this even more
#creating a table of the rows that have to do woth coal emission
CO2_coal = coal_totals[coal_totals['name'].str.contains('CO2')]

In [ ]:
CO2_coal.head(3)

In [ ]:
#put the thing down, flip it, and reverse it

#droping some columns, making name clumn the index and transposing
CO2_coal = CO2_coal.drop(['units', 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T
#sorting by year
CO2_coal = CO2_coal.sort_index(axis=0)

In [ ]:
CO2_coal.columns

In [ ]:
CO2_coal

In [12]:
cols = ['Coal Residential Sector CO2 Emissions, Monthly','Coal Commercial Sector CO2 Emissions, Monthly',
        'Coal Transportation Sector CO2 Emissions, Monthly','Coal Industrial Sector CO2 Emissions, Monthly']
CO2_all = CO2_coal[cols]
CO2_all

NameError: name 'CO2_coal' is not defined

In [ ]:
CO2_all

In [ ]:
CO2_coal['Coal Residential Sector CO2 Emissions, Monthly'].count()

In [ ]:
from helper import *

In [11]:
res = clean_column(CO2_all,'Coal Residential Sector CO2 Emissions, Monthly')

NameError: name 'CO2_all' is not defined

In [ ]:
# take the residential colum and make series and drop the NANs
res = CO2_coal['Coal Residential Sector CO2 Emissions, Monthly'].sort_index()
#it turns out the 'NA' values are just strings  so to use nan methods i will have to convert the string to np.NAN
res.dropna()

In [ ]:
res=res.replace('NA',float('NAN'))

In [ ]:
res.isnull().sum()

In [ ]:
len(res)

In [ ]:
res=res.dropna()
len(res)

In [ ]:
res=res.reset_index()

In [ ]:
res[-40:]

In [ ]:
#res[res['Coal Residential Sector CO2 Emissions, Monthly']==0.0]
#filter(res, res['Coal Residential Sector CO2 Emissions, Monthly']>0)
#res = res[(res!= 0).any()]
res=res[res['Coal Residential Sector CO2 Emissions, Monthly']>0]

In [ ]:
res.shape

In [ ]:
# this should interpolate 112 values out of 602
x = res['index']
y_res =res['Coal Residential Sector CO2 Emissions, Monthly']

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(10,5)

axs.plot(x,y_res,'o')
axs.set_title('emissions from residensial coal burning')
axs.set_xlabel('year+month')
axs.set_ylabel('million meric tons of CO2')
#axs.set_xticks(rotation=90)
axs.xaxis.set_major_locator(plt.MaxNLocator(20))
plt.xticks(rotation=70)
axs.axvline('2008',color='r',linestyle='--',alpha=0.5)
axs.text('200611',.8,'2008')
plt.savefig('residential_coal_burning.png')

**There is an obvious downword trend since the 1950, but lets take a closer look in to the 2000s to compare to our coal ash data.**

In [ ]:
len(res)

In [ ]:
res_2000s = res[res.index.str.startswith('20')]

In [ ]:
len(res_2000s)

In [ ]:
res_2000s[-20:]

In [ ]:
#checking for nans
res_2000s.isna().sum()

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(10,6)

axs.plot(res_2000s.index,res_2000s.values,'o')
axs.set_title('CO2 from residential coal burning')
axs.set_xlabel('year+month')
axs.set_ylabel('million meric tons of CO2')
#axs.set_xticklabels(res_2000s.index, rotation=90);
axs.xaxis.set_major_locator(plt.MaxNLocator(12))
axs.axvline('2008',color='r',linestyle='--',alpha=0.5)
plt.savefig('co2_res_2000.png');

**The red dashed line is right at 2008** once again the reporting has drastically changed.

Lets look at CO2 from other sectors.

In [ ]:
#Coal Electric Power Sector CO2 Emissions, Monthly
CO2_from_electric = CO2_coal['Coal Electric Power Sector CO2 Emissions, Monthly'].sort_index()

In [ ]:
#checking for nans
CO2_from_electric.isna().sum()

In [ ]:
#checking for non float
CO2_from_electric[type(CO2_from_electric.values) != float]

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(10,6)

axs.plot(CO2_from_electric.index,CO2_from_electric.values,'o')
axs.set_title('CO2 from coal burning electric power plants')
axs.set_xlabel('year+month')
axs.set_ylabel('million meric tons of CO2')
#axs.set_xticklabels(res_2000s.index, rotation=90);
axs.xaxis.set_major_locator(plt.MaxNLocator(12))
axs.axvline('2008',color='r',linestyle='--',alpha=0.5);
plt.xticks(rotation=70)
plt.savefig('co2_coal_electric.png');

**This look like reporting in the sector was good. and right at 2008 emission droped drastically. This is very exciting.**

lets see what else is in our totals.json

In [ ]:

#droping some columns, making name clumn the index and transposing
wind_df = totals[totals['name'].str.contains('Wind')].drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)

In [ ]:
wind_df.head(20)

There are alot of nans and zeros becacause are data starts in the 1950s. lets look at the 2000s

In [ ]:
wind_2000s = wind_df[wind_df.index.str.startswith('20')]

In [ ]:
#wind power df
wind_2000s

In [ ]:
#solar power from 2000s
solar_df = totals[totals['name'].str.contains('Solar')].drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
solar_2000s = solar_df[solar_df.index.str.startswith('20')]

In [ ]:
#uclear power in the 2000s
nuclear_df = totals[totals['name'].str.contains('Nuclear')].drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
nuclear_2000s = nuclear_df[nuclear_df.index.str.startswith('20')]
#totals[totals['name'].str.contains('Nuclear')]

In [ ]:
#hydroelectric powe in the 2000s
hydro_df = totals[totals['name'].str.contains('Hydroelectric')].drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
hydro_2000s = hydro_df[hydro_df.index.str.startswith('20')]

In [ ]:
# creating a sub df of geothermal energy in the 2000s
geotherm_df = totals[totals['name'].str.contains('Geothermal')].drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
geotherm_2000s = geotherm_df[geotherm_df.index.str.startswith('20')]

checking for other formes of reneable energy. I am perposly leaving out "biomass burning" becasue resent studies show that it is not good for the environmanet

In [ ]:
totals[totals['name'].str.contains('Tidal')]

In [ ]:
totals[totals['name'].str.contains('Ocean')]

In [ ]:
totals[totals['name'].str.contains('Wave')]

**Lets plot the consumption/production column from each green sector. I believe this will give us a windo into the future of grean energy. are we using it faster or slower then we are producing it?**

In [ ]:
#create x and y for wind
x = wind_2000s.index
y_wind = wind_2000s['Wind Energy Consumption/Production, Monthly'] 
#wind_2000s.columns

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(8,6)

marker_size = 3
axs.scatter(x,y_wind,label='wind',s=marker_size)
axs.scatter(x,solar_2000s['Solar/PV Energy Consumption/Production, Monthly'],label='solar/pv',s=marker_size)
axs.scatter(x,nuclear_2000s['Nuclear Electric Power Consumption/Production, Monthly'],label='nuclear',s=marker_size)
axs.scatter(x,hydro_2000s['Hydroelectric Power Consumption/Production, Monthly'],label='hydro',s=marker_size)
axs.scatter(x,geotherm_2000s['Geothermal Energy Consumption/Production, Monthly'],label='geotherm',s=marker_size)

axs.set_title('Renewable energy Consumtion/Production')
axs.set_xlabel('year+month')
axs.set_ylabel('Trillion BTU')
#axs.set_xticklabels(res_2000s.index, rotation=90);
axs.xaxis.set_major_locator(plt.MaxNLocator(12))
axs.axvline('2008',color='r',linestyle='--',alpha=0.5);
plt.xticks(rotation=70)
plt.legend()
#axs.axhline(0,color='k')
plt.savefig('renewable_production.png');

In [ ]:
geotherm_2000s.columns

Lets compare coal for electric power and nuclear for electric power

In [ ]:
nuclear_2000s.head(20)

In [ ]:
#nuc_to_electric
nuc_to_electric = nuclear_2000s['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly']

In [ ]:
type(nuc_to_electric)

In [ ]:
# lets just try taking out the zeros
nuc_to_electric = nuc_to_electric[nuc_to_electric !=0]

In [ ]:
nuc_to_electric.index

In [ ]:
pd.to_datetime(nuc_to_electric.index,format='%Y%m')

In [ ]:
nuc_to_electric.index  =pd.to_datetime(nuc_to_electric.index,format='%Y%m')

In [ ]:
nuc_to_electric = nuc_to_electric.reset_index()
#nuc_to_electric

In [ ]:
nuc_to_electric['year'] = nuc_to_electric['index'].dt.year
nuc_to_electric['month'] = nuc_to_electric['index'].dt.month

In [ ]:
#nuc_to_electric

In [ ]:
nuc_to_electric['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'] =nuc_to_electric['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'].astype(float)

In [ ]:
#nuc_to_electric.info()

In [ ]:
nuc_ave_month = nuc_to_electric.groupby(['month']).mean()

In [ ]:
#nuc_ave_month.head(3)

In [ ]:
#lets do the same for coal to electric
coal_totals
coal_df = coal_totals.drop([ 'data','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
coal_2000s = coal_df[coal_df.index.str.startswith('20')]
coal_2000s['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly']

In [ ]:
coal_to_electric = coal_2000s['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly']
coal_to_electric = coal_to_electric[coal_to_electric !=0]
coal_to_electric.index  =pd.to_datetime(coal_to_electric.index,format='%Y%m')
coal_to_electric = coal_to_electric.reset_index()
coal_to_electric['year'] = coal_to_electric['index'].dt.year
coal_to_electric['month'] = coal_to_electric['index'].dt.month
coal_to_electric['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'] =coal_to_electric['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'].astype(float)
coal_ave_month = coal_to_electric.groupby(['month']).mean()

In [ ]:
fig, axs = plt.subplots(1,2)
fig.set_size_inches(9,3.5)

ticks =['Jan','Feb','March','Aprl','May','June','July','Aug','Sep','Oct','Nov','Dec']
axs[0].bar(coal_ave_month.index,coal_ave_month['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'],label='coal',align='center',tick_label=ticks)
axs[0].set_title('Dirty                              ')


axs[1].set_title('                              clean')
axs[1].bar(nuc_ave_month.index, nuc_ave_month['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'],label='Nuclear',align='center',tick_label=ticks)

axs[0].legend()
axs[1].legend()
fig.suptitle('average monthly production',size=16)
axs[0].set_ylabel('Trillion BTUs')
plt.xticks(rotation=70)
plt.tight_layout();

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(10,4)

ticks =['Jan','Feb','March','Aprl','May','June','July','Aug','Sep','Oct','Nov','Dec']
axs.bar(coal_ave_month.index,coal_ave_month['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'],label='coal',align='center',tick_label=ticks)
#axs.set_title('Dirty                              ')


#axs[1].set_title('                              clean')
axs.bar(nuc_ave_month.index, nuc_ave_month['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'],label='Nuclear',align='center',tick_label=ticks)

#axs[0].legend()
axs.legend()
axs.set_title('Average monthly production (17 years)',size=16)
axs.set_ylabel('Trillion BTUs')
plt.xticks(rotation=70)
plt.tight_layout()
plt.savefig('17yr-monthly-coal-nuc.png');

In [ ]:
ave_coal_1year = coal_ave_month[coal_ave_month['year']==2017]
ave_nuc_1year = nuc_ave_month[nuc_ave_month['year']==2017]

In [ ]:
coal_ave_month

In [ ]:
# taking just nuclear averageing my month in 2016
nuclear_2016 = nuclear_df[nuclear_df.index.str.startswith('2016')]
nuc_to_electric2 = nuclear_2016['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly']
nuc_to_electric2 = nuc_to_electric2[nuc_to_electric2 !=0]
nuc_to_electric2.index  =pd.to_datetime(nuc_to_electric2.index,format='%Y%m')
nuc_to_electric2 = nuc_to_electric2.reset_index()
nuc_to_electric2['year'] = nuc_to_electric2['index'].dt.year
nuc_to_electric2['month'] = nuc_to_electric2['index'].dt.month
nuc_to_electric2['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'] =nuc_to_electric2['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'].astype(float) 
nuc_ave_month2 = nuc_to_electric2.groupby(['month']).mean()

nuc_ave_month2

In [ ]:
#coal 2016
coal_2016 = coal_df[coal_df.index.str.startswith('2016')]
coal_2016['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly']
coal_to_electric2 = coal_2016['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly']
coal_to_electric2 = coal_to_electric2[coal_to_electric2 !=0]
coal_to_electric2.index  =pd.to_datetime(coal_to_electric2.index,format='%Y%m')
coal_to_electric2 = coal_to_electric2.reset_index()
coal_to_electric2['year'] = coal_to_electric2['index'].dt.year
coal_to_electric2['month'] = coal_to_electric2['index'].dt.month
coal_to_electric2['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'] =coal_to_electric2['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'].astype(float)
coal_ave_month2 = coal_to_electric2.groupby(['month']).mean()
coal_ave_month2

In [ ]:
fig, axs = plt.subplots()
fig.set_size_inches(9,3.5)

ticks =['Jan','Feb','March','Aprl','May','June','July','Aug','Sep','Oct','Nov','Dec']
axs.bar(coal_ave_month2.index,coal_ave_month2['Coal Consumption for Electricity Generation, Electric Power Sector, Monthly'],label='coal',align='center',tick_label=ticks)


axs.bar(nuc_ave_month2.index, nuc_ave_month2['Nuclear Electric Power Consumed by the Electric Power Sector, Monthly'],label='Nuclear',align='center',tick_label=ticks)


axs.legend()
axs.set_title('average monthly production 2016',size=16)
axs.set_ylabel('Trillion BTUs')
plt.xticks(rotation=70)
#plt.tight_layout();
plt.savefig('2016-coal-nuc.png')

**moving on to percentages of clean and dirty energy per year**

TOTAL ENERGY colums from total.json
 - Total Energy Consumed by the Transportation Se...(these are all annual)
 - Total Energy Consumed by the Transportation Se...
 - Total Energy Consumed by the Commercial Sector...
 - Total Energy Consumed by the Commercial Sector...
 - Total Energy Consumed by the Industrial Sector...
 - Total Energy Consumed by the Industrial Sector...
 - Total Energy Consumed by the Residential Secto...
 - Total Energy Consumed by the Residential Secto...

TOTAL CLEAN ENERGY columns from total.json<br>
*note: eia considers renewables to be: solar, wind, hydro, geothermal other*
 - Total Renewable Energy Consumption, Annual 	Trillion Btu
 - Nuclear Electric Power Consumption/Production,.  monthly

In [ ]:
# making a total_energy df
total_energy = totals[(totals['name'].str.contains('Total Energy Consumed by the')) &(totals['name'].str.contains('Annual'))]
totals_df= total_energy.drop([ 'data','units','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
totals_df = totals_df[totals_df !=0]
totals_df.dropna(axis=0,how='all',inplace=True)
totals_df['Total Energy'] = totals_df[list(totals_df.columns)].sum(axis=1)
totals_df.index.dtype

In [ ]:
# data frame of anual nuclear energy
total_nuc = totals[totals['name'].str.contains('Nuclear Electric Power Consumption/Production')]
total_nuc = total_nuc.drop([ 'data','units','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)

total_nuc = total_nuc[total_nuc.index.str.len() > 4]
total_nuc.index  = pd.to_datetime(total_nuc.index,format='%Y%m')
total_nuc = total_nuc.reset_index()

total_nuc['year'] = total_nuc['index'].dt.year
total_nuc['month'] = total_nuc['index'].dt.month
total_nuc.drop(['index','month'],axis=1,inplace=True)

total_nuc = total_nuc.groupby('year').sum()
total_nuc['Total Nuclear'] = total_nuc['Nuclear Electric Power Consumption/Production, Monthly']
total_nuc.drop('Nuclear Electric Power Consumption/Production, Monthly',axis=1,inplace=True)
total_nuc.index.rename('year',inplace=True)
total_nuc.head()

In [ ]:
total_nuc.shape

In [ ]:
total_nuc.index = total_nuc.index.map(str)
total_nuc.index.dtype

In [ ]:
# df of total renewable consumtion
total_renew = totals[totals['name'].str.contains('Total Renewable Energy Consumption, Annual')]
total_renew = total_renew.drop([ 'data','units','last_updated', 'f','start','end'], axis=1).set_index('name').T.sort_index(axis=0)
total_renew = total_renew[total_renew.index.str.len() == 4]
total_renew = total_renew.reset_index()
total_renew['Total Renewable'] = total_renew['Total Renewable Energy Consumption, Annual']
total_renew.drop('Total Renewable Energy Consumption, Annual',axis=1, inplace=True)
total_renew = total_renew.set_index('index')
total_renew.index.rename('year',inplace=True)
#total_renew.index.astype('Int64')
total_renew.index.dtype

In [ ]:
# I am goin to left join everthing to nuclear data set becasue it is recorded only after 1979 as opposed to the other df who start reporting at 1949
total_clean = total_nuc.join(total_renew,how='inner')
totals_df = totals_df.join(total_clean,how='inner')

In [ ]:
totals_df['Total Clean'] = totals_df['Total Nuclear'] + totals_df['Total Renewable']
totals_df['Percent Clean'] = totals_df['Total Clean']/totals_df['Total Energy']
totals_df

In [ ]:
#Lets see how it looks
import matplotlib.pyplot as plt

fig, axs = plt.subplots()
fig.set_size_inches(8,3)
x = totals_df.index
y = totals_df['Percent Clean']
axs.plot(x,y)
plt.title('Percent of our US energy consumtion from clean energy')
axs.xaxis.set_major_locator(plt.MaxNLocator(16))
plt.xticks(rotation=70)
#plt.tight_layout();
plt.savefig('percent-clean.png')
;